package.name=com.beta9.beta
domain.limit=99999
enable.disableApps=true
enable.appComponent=true
appComponent.showSystemApps=true
default.host=https://raw.githubusercontent.com/Virkkunen/adhell/main/hosts_generator/hosts
