name: hosts_generator

on:
  schedule:
    - cron: '0 12 * * SUN'
  push:
    branches: 
      - "main"

jobs:
  hosts_generator:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} 
        
      - name: Update hosts
        run: powershell hosts_generator/generator/build_hosts.ps1
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update hosts 
