name: CI
on:
  schedule:
    - cron: '0 12 * * SUN'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update hosts
        run: powershell hosts_generator/generator/build_hosts.ps1
      - name: push
        uses: actions/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Update hosts'
          add: .
          name: Virkkunen
          email: fredvrkknn@pm.me          
